name: Shared - Danger JS
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize, ready_for_review]

jobs:
  should-run-checks:
    name: Determine if checks should run
    uses: ./.github/workflows/should_run_pr_checks.yml
  danger:
    name: Danger JS
    needs: should-run-checks
    if: needs.should-run-checks.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: danger/danger-js@13.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "--dangerfile duckduckgo/danger-settings/org/allPRs.ts@main"
