name: iOS - Make TestFlight Experimental Build

on:
  workflow_dispatch:

jobs:
  build-experimental:
    runs-on: ubuntu-latest
    name: Build Experimental
    steps:
    - name: Placeholder
      run: echo "WIP"
      