name: macOS - Integration Tests

defaults:
  run:
    working-directory: macOS

on:
  push:
    # branches: [ main, "release/macos/**", "hotfix/macos/**" ]
    # paths:
      # - 'SharedPackages/**'
      # - 'macOS/**'
  pull_request:
    paths:
      - '.github/**'
      - 'SharedPackages/**'
      - 'macOS/**'
  workflow_call:
    inputs:
      branch:
        description: "Branch name"
        required: false
        type: string
    secrets:
      APPLE_API_KEY_BASE64:
        required: true
      APPLE_API_KEY_ID:
        required: true
      APPLE_API_KEY_ISSUER:
        required: true
      ASANA_ACCESS_TOKEN:
        required: true
      MATCH_PASSWORD:
        required: true
      SSH_PRIVATE_KEY_FASTLANE_MATCH:
        required: true

env:
  flavor: Non-Sandbox
  scheme: macOS Browser
  integration_tests_target: Integration Tests
  cache_key:
    
jobs:

  build-for-testing:
    name: Build for Testing

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     flavor: [ "Sandbox", "Non-Sandbox" ]
    #     include:
    #       - scheme: macOS Browser
    #         flavor: Non-Sandbox
    #       - scheme: macOS Browser App Store
    #         flavor: Sandbox
    #       - active-arch: YES
    #         flavor: Non-Sandbox
    #       - active-arch: NO
    #         flavor: Sandbox
    #       - integration-tests-target: Integration Tests
    #         flavor: Non-Sandbox
    #       - integration-tests-target: Integration Tests App Store
    #         flavor: Sandbox
    #       - cache-key:
    #         flavor: Non-Sandbox
    #       - cache-key: sandbox-
    #         flavor: Sandbox

    runs-on: macos-15
    timeout-minutes: 30

    outputs:
      artifact_id: ${{ steps.upload-derived-data.outputs.artifact-id }}

    steps:
    - name: Register SSH key for certificates repository access
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}

    - name: Check out the code
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check out the code
      if: github.event_name != 'pull_request' && github.event_name != 'push'
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ inputs.branch || github.ref_name }}

    - name: Set up fastlane
      run: bundle install

    - name: Sync code signing assets
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
      run: bundle exec fastlane sync_signing_ci

    - name: Set cache key hash
      run: |
        has_only_tags=$(jq '[ .pins[].state | has("version") ] | all' DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved)
        if [[ "$has_only_tags" == "true" ]]; then
          # hashFiles does not respect the working directory, so the full path must be specified
          echo "cache_key_hash=${{ hashFiles('macOS/DuckDuckGo-macOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}" >> $GITHUB_ENV
        else
          echo "Package.resolved contains dependencies specified by branch or commit, skipping cache."
        fi

    - name: Cache SPM
      if: env.cache_key_hash
      uses: actions/cache@v4
      with:
        path: macOS/DerivedData/SourcePackages
        key: ${{ runner.os }}-macos-${{ env.cache_key }}${{ env.cache_key_hash }}
        restore-keys: |
          ${{ runner.os }}-macos-${{ env.cache_key }}

    - name: Select Xcode
      uses: ./.github/actions/select-xcode-version

    - name: Build for testing
      run: |
        set -o pipefail && xcodebuild build-for-testing \
          -scheme "${{ env.scheme }}" \
          -derivedDataPath "DerivedData" \
          -configuration "CI" \
          -skipPackagePluginValidation -skipMacroValidation \
          ENABLE_TESTABILITY=true \
        | tee ${{ env.flavor }}-unittests-build-xcodebuild.log \
        | xcbeautify
        rm -rf DerivedData/ModuleCache.noindex

    - name: Upload Derived Data artifact
      id: upload-derived-data
      uses: actions/upload-artifact@v4
      with:
        name: DerivedData
        path: ${{ github.workspace }}/macOS/DerivedData
        retention-days: 1
        compression-level: 9

  # This job sets up the matrix strategy arguments for the ui-tests job
  setup-tests:
    name: Set up tests list
    runs-on: macos-15
    outputs:
      test: ${{ steps.list-tests.outputs.test }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List tests
        id: list-tests
        run: |
          # Find all test files in the UITests directory
          # This assumes that all test files are named *Tests.swift and are put directly in the UITests directory
          test_names="$(find IntegrationTests -type f -name '*Tests.swift' | xargs basename | sed 's/\.swift//')"
          test=$(echo $test_names | jq -cR 'split(" ")')
          echo "test=${test}" >> $GITHUB_OUTPUT

  tests:
    name: ${{ matrix.test }} (Non-Sandbox)
    needs: [build-for-testing, setup-tests]
    runs-on: macos-15-xlarge
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.setup-tests.outputs.test) }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test }}
      cancel-in-progress: true

    timeout-minutes: 15

    outputs:
      commit_author: ${{ steps.fetch_commit_author.outputs.commit_author }}

    steps:
    - name: Register SSH key for certificates repository access
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}

    - name: Check out the code
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check out the code
      if: github.event_name != 'pull_request' && github.event_name != 'push'
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: ${{ inputs.branch || github.ref_name }}
  
    - name: Set up fastlane
      run: bundle install

    - name: Sync code signing assets
      env:
        APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
      run: |
        bundle exec fastlane sync_signing_ci

    - name: Download and unzip artifact
      uses: actions/download-artifact@v4
      with:
        name: DerivedData
        path: ${{ github.workspace }}/macOS/DerivedData

    - name: Run integration tests
      run: |
        set -o pipefail && xcodebuild test-without-building \
          -scheme "${{ env.scheme }}" \
          -derivedDataPath "DerivedData" \
          -configuration "CI" \
          -skipPackagePluginValidation -skipMacroValidation \
          ENABLE_TESTABILITY=true \
          "-only-testing:${{ env.integration_tests_target }}/${{ matrix.test }}" \
          | tee ${{ matrix.test }}-${{ env.flavor }}-integrationtests-xcodebuild.log \
          | xcbeautify --report junit --report-path . --junit-report-filename ${{ matrix.test }}-${{ env.flavor }}-integrationtests.xml

    - name: Update Asana with failed unit tests
      if: always() # always run even if the previous step fails
      env:
        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
      run: |
        # Extract failed tests from the junit report
        # Only keep failures unique by classname and name (column 1 and 2 of the yq output)
        yq < "${{ matrix.test }}-${{ env.flavor }}-integrationtests.xml" -p xml -o json -r \
          $'[.testsuites.testsuite[].testcase] | flatten | map(select(.failure) | .+@classname + " " + .+@name + " \'" + .failure.+@message + "\' ${{ env.WORKFLOW_URL }}") | .[]' \
          | sort -u -k 1,2 \
          | xargs -L 1 ./scripts/report-failed-unit-test.sh

    - name: Prepare test report
      id: prepare-test-report
      if: always()
      run: |
        file="${{ matrix.test }}-${{ env.flavor }}-integrationtests.xml"
        echo "file=$file" >> $GITHUB_OUTPUT
        # Replace the default test suite name with the test id for better grouping in the test report
        sed -i '' "s/Selected tests/${{ matrix.test }} (${{ env.flavor }})/" "$file"

    # Upload test report as artifact for the test-report job
    # that publishes a combined report for all test cases
    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "testreport-${{ matrix.test }}-${{ env.flavor }}"
        path: "macOS/${{ steps.prepare-test-report.outputs.file }}"
        retention-days: 1

    - name: Upload logs when workflow failed
      uses: actions/upload-artifact@v4
      if: failure() || cancelled()
      with:
        name: "BuildLogs ${{ matrix.test }} (${{ env.flavor}})"
        path: |
          macOS/*xcodebuild.log
          macOS/DerivedData/Logs/Test/*.xcresult
          ~/Library/Logs/DiagnosticReports/*
        retention-days: 7

    - name: Fetch latest commit author
      if: always() && github.ref_name == 'main'
      id: fetch_commit_author
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        head_commit=$(git rev-parse HEAD)
        author=$(gh api https://api.github.com/repos/${{ github.repository }}/commits/${head_commit} --jq .author.login)
        echo "commit_author=${author}" >> $GITHUB_OUTPUT

  test-report:
    name: Report test results
    if: always()
    needs: [build-for-testing, tests]
    runs-on: ubuntu-latest

    steps:
    - name: Download test reports
      uses: actions/download-artifact@v4
      if: always()
      with:
        pattern: "testreport-*"
        merge-multiple: true

    - name: Publish tests report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        check_name: Tests Report
        report_paths: "*.xml"
        check_retries: true
        group_reports: false
        flaky_summary: true
        verbose_summary: false
        include_time_in_summary: true
        skip_annotations: true

    - name: Delete Derived Data artifact
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.actions.deleteArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: ${{ needs.build-for-testing.outputs.artifact_id }}
          });

  create-asana-task:
    name: Create Asana Task
    needs: [tests]

    if: failure() && github.ref_name == 'main' && github.run_attempt == 1

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Create Asana Task
        uses: ./.github/actions/asana-failed-pr-checks
        with:
          action: create-task
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section-id: ${{ vars.APPLE_CI_FAILING_TESTS_MACOS_POST_MERGE_SECTION_ID }}
          commit-author: ${{ needs.tests.outputs.commit_author }}

  close-asana-task:
    name: Close Asana Task
    needs: [tests]

    if: success() && github.ref_name == 'main' && github.run_attempt > 1

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Close Asana Task
        uses: ./.github/actions/asana-failed-pr-checks
        with:
          action: close-task
          asana-access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
          asana-section-id: ${{ vars.APPLE_CI_FAILING_TESTS_MACOS_POST_MERGE_SECTION_ID }}
