name: Shared - SwiftLint
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize, ready_for_review]

jobs:
  should-run-checks:
    name: Determine if checks should run
    uses: ./.github/workflows/should_run_pr_checks.yml

  swiftlint:
    name: SwiftLint
    needs: should-run-checks
    if: needs.should-run-checks.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: SwiftLint
        run: |
          set -o pipefail
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            norionomura/swiftlint:0.59.1_swift-5.9.0 \
            swiftlint --reporter github-actions-logging --strict --quiet \
            | tee >(grep -oP 'file=[^,]+,line=\d+' \
            | sed -E 's/file=([^,]+),line=([0-9]+)/\1:\2/' >&2 || true)
